### ISSUE TITLE
Spam Open Boxes

### ISSUE THREAD

**Issue by LucasHeil** [glixxzzy/blooket-hack#139]
Can You Update The Spam Open Boxes Hack For The Dino Box Please. Thanks

**Comment by godlygamer123** [comment]
yee

**Comment by CowCowCowCowCowCow** [comment]
yes pls and also for blizzard and spooky

**Comment by Hankypoo7** [comment]
cow those aren't in shop

**Comment by CowCowCowCowCowCow** [comment]
@Hankypoo7 but can you make a spam open boxes for when they are in store (they come at halloween and christmas)

**Comment by Hankypoo7** [comment]
yeah

**Comment by joseph6565665** [comment]
why dont the spam box work i tried to spam the wonderland box and it didn't work for some reason.

**Comment by CowCowCowCowCowCow** [comment]
> why dont the spam box work i tried to spam the wonderland box and it didn't work for some reason.

you need to put javascript: first
