### ISSUE TITLE
chest esp 

### ISSUE THREAD

**Issue by jb2465** [glixxzzy/blooket-hack#141]
the chest esp is not working right now can you fix it please

**Comment by Hankypoo7** [comment]
yes we will work on a fix

**Comment by ratlicker69420** [comment]
watch me whip, now watch me nae nae

**Comment by chazzman42** [comment]
> 

Go here and all the hacks are working 
https://schoolcheats.net/blooket/

**Comment by IdkHowToCode-JustAChromebookGuy** [comment]
the chest esp is still not working. please fix it. player set gold is also not working. please fix that as well.
