### ISSUE TITLE
A lot of hacks not working

### ISSUE THREAD

**Issue by SuhrudJoshi** [glixxzzy/blooket-hack#173]
Hey a lot of hacks aren't working such as crypto hack, Cafe, tower defense, and tons more. for example in Cafe it doesn't work when it asks me to upgrade some stuff. When I give unlimited coins in tower defense it doesnt work. in crypto hack giving crypto and finding others passwords don't work either pls fix them

**Comment by SuhrudJoshi** [comment]
NVM it works all of it works

**Comment by oneenterprisestech** [comment]
Blooket just updated. Some of the hacks don't work now.
