### ISSUE TITLE
Blocked

### ISSUE THREAD

**Issue by USSGreenhornet** [glixxzzy/blooket-hack#179]
Github has been blocked at my school

**Comment by Harrassing-idiots** [comment]
Use https://uv-unb.fo-od.repl.co/

**Comment by Harrassing-idiots** [comment]
It should unblock everything, from roblox to the hub

**Comment by MuhammedSamana** [comment]
> Use https://uv-unb.fo-od.repl.co/

https://uv-unb.fo-od.repl.co/ does not work anymore
