### ISSUE TITLE
There is no deceptive dinos hack

### ISSUE THREAD

**Issue by Wilke000** [glixxzzy/blooket-hack#204]
I'm sure you are working on it, but yea...

**Comment by MicroXman3** [comment]
I just reached out to two people we will create one don't worry. It might take a day or two but we will make one.

**Comment by glixxzzy** [comment]
[@MicroXman3](https://github.com/MicroXman3) There's no way your trying to advertise someone else's hacks here..

**Comment by Jogvi** [comment]
wat? he litteraly asked for a hack on the new gamemode but yes pls make the hack
