### ISSUE TITLE
token hack

### ISSUE THREAD

**Issue by Carter01cccccc** [glixxzzy/blooket-hack#209]
Make the token hack to 1000 and make it to were you could do it when ever and not have to wait till the next game

**Comment by glixxzzy** [comment]
None of this is possible.

**Comment by glixnex** [comment]
let him be gixxzzy is trying hard as he can he is the one coding ok? @Carter01cccccc

**Comment by dubfib** [comment]
> Make the token hack to 1000 and make it to were you could do it when ever and not have to wait till the next game

blooket only allows for 500 tokens

**Comment by glixnex** [comment]
yes @dubfib
