### ISSUE TITLE
something suspicious

### ISSUE THREAD

**Issue by dubfib** [glixxzzy/blooket-hack#213]
why would gliz make repos and fork them from other blooket hacks...
+ https://github.com/glixxzzy/blo- (https://web.archive.org/web/20220529042613/https://github.com/glixxzzy/blo-)
+ https://github.com/glixxzzy/Blooket-hacks-Hankypoo7- (https://web.archive.org/web/20220529042745/https://github.com/glixxzzy/Blooket-hacks-Hankypoo7-)
+ https://github.com/glixxzzy/glizzy_blooket (https://web.archive.org/web/20220529042835/https://github.com/glixxzzy/glizzy_blooket)

**Comment by glixxzzy** [comment]
None of those hacks work... I'm getting copies of my original work.

**Comment by Blooper-glooper** [comment]
> why would gliz make repos and fork them from other blooket hacks...
> 
> * https://github.com/glixxzzy/blo- (https://web.archive.org/web/20220529042613/https://github.com/glixxzzy/blo-)
> * https://github.com/glixxzzy/Blooket-hacks-Hankypoo7- (https://web.archive.org/web/20220529042745/https://github.com/glixxzzy/Blooket-hacks-Hankypoo7-)
> * https://github.com/glixxzzy/glizzy_blooket (https://web.archive.org/web/20220529042835/https://github.com/glixxzzy/glizzy_blooket)

you know hes not the actual gliz
