### ISSUE TITLE
when will you stop logging ips?

### ISSUE THREAD

**Issue by l2vy7** [glixxzzy/blooket-hack#217]
cringe.

**Comment by dubfib** [comment]
> 

evidence? prove

**Comment by l2vy7** [comment]
> > 
> 
> evidence? prove

xotic had his ip logged, glizzy works in association with schoolcheats (look at their TOS)  
+ you coping and seething

**Comment by glixxzzy** [comment]
You realize you can't do shit with a public ip righy? I don't log ips but ebwry website logs your ip when you visiy it, its almost imposible to get a privafe ip which is what actually does damage.
