### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by Angelio-Mustachio-Coder** [glixxzzy/blooket-hack#218]
When I use These hacks, My Pc Generates a box where the "Gliz" thing is supposed to go, and it shuts down my blooket since I can't tap anything.

**Comment by Angelio-Mustachio-Coder** [comment]
![Screenshot 2022-05-31 103310](https://user-images.githubusercontent.com/106037601/171199140-9bc6289a-1c0f-4b65-901c-ca90d0c99441.png)

**Comment by glixxzzy** [comment]
If it's a bookmark it may be an out dated hack, otherwise just refresh the page.
