### ISSUE TITLE
Please make a hack to make your chances of getting better blooks higher?

### ISSUE THREAD

**Issue by MrGamer-FS** [glixxzzy/blooket-hack#232]
Like in the Safari box there is the Rainbow Panda which is 0.02% chance of getting it. Is there a way to make that like 100% or just raise it in general?

**Comment by saiparimi123** [comment]
Yes please do

**Comment by Angelio-Mustachio-Coder** [comment]
This is Impossible, as you would have to breech the Blooket data centers. And you probably would be found and Banned.

**Comment by v8f** [comment]
> Like in the Safari box there is the Rainbow Panda which is 0.02% chance of getting it. Is there a way to make that like 100% or just raise it in general?

not possible. absolutely impossible and you have to be a blooket admin inorder to do this
