### ISSUE TITLE
You didn’t make the Deceptive Dinos Hack. I made it.

### ISSUE THREAD

**Issue by rxzyx** [glixxzzy/blooket-hack#242]
Hello! I noticed that the hack for Deceptive Dinos is actually my hack… Can you please give me credit? Thank you for your time.

**Comment by rxzyx** [comment]
getFossils is my Fossil Hack and fossilMultiplier is my Fossil Multiplier.

**Comment by rxzyx** [comment]
As the evidence was staten, if you do not comply with giving me credit on both your README.md and for the deceptive-dinos README.md then I will have no choice but to issue a DMCA Takedown.

**Comment by glixxzzy** [comment]
Hey bud! I didn't take yours. And another think, we both have a M.I.T license so guess what? Even if I didn't make it I still could take it 🤣🤣🤣🤣

**Comment by Angelio-Mustachio-Coder** [comment]
#1, rxzyx's hacks work better

#2 You STOLE  them from Schoolcheats

#3 Threats aren't ok, as you act like you own this app. This is a community and HankyPoo has had problems with you in the past.

**Comment by Blooper-glooper** [comment]
@Angelio-Mustachio-Coder this isn't the actual gliz he is a fake i found the actual one

**Comment by yedonbro** [comment]
im gonna put this on your discord

**Comment by glixxzzy** [comment]
You realize I'm real right? and I provide to school cheats.
