### ISSUE TITLE
!!Read!!

### ISSUE THREAD

**Issue by v8f** [glixxzzy/blooket-hack#257]
I found out about the no delay/cool down thing months ago when messing with javascript . I ended up making my own script for it. If you do not *credit* or *remove* the hack then I will take it down myself. I put this script in a respitory I had file adding access in (the script got removed).. I don't mind you putting it there , just credit me for the output and layout..

**Comment by glixxzzy** [comment]
Dawg I didn't get it from you, it's not hard to code this kind of stuff.
