### ISSUE TITLE
Apparently this glixxzzy is fake?

### ISSUE THREAD

**Issue by Glitchhackers** [glixxzzy/blooket-hack#334]
i don't think i can sorry

_Originally posted by @glixxzzy in https://github.com/glixxzzy/blooket-hack/discussions/241#discussioncomment-2941457_

**Comment by glixxzzy** [comment]
Hey! This user created a profile and stole all my stuff and is now saying I'm fake so I would like to say it is not true and they just want my identity, sorry for the confusion.

**Comment by glixxzzy** [comment]
I am the only real gliz, if a change must happen it will be announced in my Discord.

**Comment by v8f** [comment]
bro you arent real
