### ISSUE TITLE
what are you doing?

### ISSUE THREAD

**Issue by v8f** [glixxzzy/blooket-hack#337]
why did you take down my issue? also, none of this is yours.. :joy:

**Comment by v8f** [comment]
Also just for your knowledge i have a thing with all these hacks, and you forgot to credit someone :joy: Good luck trying to survive what's going to happen next

**Comment by glixxzzy** [comment]
I'm gliz and it literally says on my hacks, I make all of these and provide them to schoolcheats so idk what your up on.

**Comment by gIizxzy** [comment]
no your not.
