### ISSUE TITLE
Imagine stealing @rxzyx's code LMAOOOO

### ISSUE THREAD

**Issue by cryingman69** [glixxzzy/blooket-hack#342]
nothing more to say

**Comment by cryingman69** [comment]
lmaooo imagine stealing code

**Comment by cryingman69** [comment]
FAKE glixxzzy  (lol-poo) = POO

**Comment by cryingman69** [comment]
imagine

**Comment by cryingman69** [comment]
bro probably sleeps with his uncle

**Comment by cryingman69** [comment]
stop stealing code it is literally copyrighted 
I bet you have daddy issues

**Comment by glixxzzy** [comment]
proof?
