### ISSUE TITLE
take down this repository

### ISSUE THREAD

**Issue by GooseterV** [glixxzzy/blooket-hack#345]
You honestly don't know what you're getting into by having this up. You know gliz got a c&d back in february (cease in desist) and i don't know if you don't realize how severe things can get if he were to bring his things back, but by impersonating him, you could get him into major legal trouble, and you yourself can get into legal trouble by keeping this up. I've already contacted github and can get the owner of blooket to send you, "the real gliz" (you're fake) a c&d which would also make YOU have to stop doing this. For one, the hacks are ruining the game and while they're mostly harmless, upload them on your own repository you weirdo. What's the point of publishing someone else's stuff, under THEIR name, and expect to get any credit for it? Second of all, if you were actually the "real gliz" then you'd be breaking github tos, and you are not eligible for major legal repercussions. I'd suggest whoever you are, whether you actually are "gliz" or whether you're just another impersonator, to stop this nonsense and at least upload under your own name. thanks - goose

**Comment by GooseterV** [comment]
PS: i've already filed a report with github and they'll be taking action soon so i recommend not being an idiot about all this.

**Comment by glixxzzy** [comment]
Sorry to tell you but I am gliz, I provide to school cheats and I'm not scared of a c&d, I only got it for another reason not for my hacks. I am not scared of this.

**Comment by Blooper-glooper** [comment]
There’s lots of proof against him and he is definitely a fake many people have asked gliz himself I believe

**Comment by Blooper-glooper** [comment]
> Sorry to tell you but I am gliz, I provide to school cheats and I'm not scared of a c&d, I only got it for another reason not for my hacks. I am not scared of this.

We all know you are a fake

**Comment by GooseterV** [comment]
he is a fake, and i can contact the real gliz on discord anytime if i want to, and yeah, the c&d was from your hacks, as someone who witnessed ben sending it to gliz, i know what it was for. not to mention  being "scared" of a c&d. of course nobody is scared of it, its a warning, but not heeding that warning results in punishment...

**Comment by UndercoverGoose** [comment]
[https://docs.google.com/document/d/1Med4Qpjl2Fg9R-wev2VvcHaEdarpfMG5Xn6HxwbzbDM/edit?usp=sharing](https://docs.google.com/document/d/1Med4Qpjl2Fg9R-wev2VvcHaEdarpfMG5Xn6HxwbzbDM/edit?usp=sharing)
