### ISSUE TITLE
Spam Open Boxes Not Working

### ISSUE THREAD

**Issue by theotarr** [glixxzzy/blooket-hack#349]
I believe Blooket pushed some new code that breaks spam opening boxes and some other hacks since I used this hack yesterday with no trouble. Nevertheless here are the errors:
```
GET https://api.blooket.com/api/games?gameId=628bf0a5f13fa30455b33c60 404 (Not Found)
```
and
```
Uncaught (in promise) SyntaxError: Unexpected token o in JSON at position 1
```

It looks like an easy fix and I'd be happy to help if I can see the decoded version of these hacks.

**PS: If possible, I recommend writing some automated tests using something like Selenium to test if there are any Javascript bugs when injecting the Blooket website.**

**Comment by glixxzzy** [comment]
fixed
