### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by yaboyvinnyp** [glixxzzy/blooket-hack#353]
I love these hacks and use them every day but I've noticed some problems.1. fishing frenzy set weight instantly bans you it happened to me twice.2. what does spam bots do.3. spam open box's also hasn't been working for me it usually does though.

**Comment by VillainsRule4000** [comment]
@yaboyvinnyp Hello!
1. Set Weight is a hack that bans you, I have requested a takedown.
2. Spam Bots makes a game have a ton of players who are nonexistent.
3. I don't know about the Spam Boxes.

**Comment by glixxzzy** [comment]
I'll look into spam boxes give me a second here.

**Comment by glixxzzy** [comment]
Spam open boxes has been fixed thank you.
