### ISSUE TITLE
you stole rxzyx deceptive dinos. I will be reporting you.

### ISSUE THREAD

**Issue by BetterCordDer** [glixxzzy/blooket-hack#355]
And it if dosen't get you banned I will send a cease and desist straight to your email.

So if you don't remove getfossils or make it so it dosen't have anyone else's code in 24 hours I will send a cease and desist to your email.

**Comment by glixxzzy** [comment]
I didn't but go ahead.

**Comment by rxzyx** [comment]
> > And it if dosen't get you banned I will send a cease and desist straight to your email.
> > So if you don't remove getfossils or make it so it dosen't have anyone else's code in 24 hours I will send a cease and desist to your email.
> 
> You know that everyone has the same code pretty much bc it is probley the easyiest one so shut up he was here first you has no valid opinion

It is obfuscation, it is random, thus; me and a couple of lads have determined that it'd be a 1 in 5.8043119544224624298785616126349e+882 chance for it to have been entirely the same obfuscated code, toodles! Also if you don't see that I replied it means that I was blocked like before 😀. You can try this yourself, you'd notice that the results are always different. [Obfuscator Link](https://obfuscator.io/)
