### ISSUE TITLE
BUG: Spam Open Blooks Not Allowing Dino Boxes To Be Opened

### ISSUE THREAD

**Issue by theotarr** [glixxzzy/blooket-hack#356]
Thanks for fixing my last issue!

But the new fix does not allow Dino boxes to be opened. I suspect that you reverted to an old version of the hack before the dino update was added. 

**As I said in my last issue, writing some automated tests would go a long way to prevent these types of easily fixable bugs.**

**Comment by glixxzzy** [comment]
Since Blooket's API has not been updated at this moment I am unable to do so at this time sorry!
