### ISSUE TITLE
Glitch: Add tokens dont work 

### ISSUE THREAD

**Issue by SoaRSniping** [glixxzzy/blooket-hack#362]
when your doing the add tokens things it leaves blooket and goes to a new page about the code is fake and not working something like that I would share a screen shot but I cant

**Comment by CrypticLucid** [comment]
my bookmarklet is working however the one on the repo isn't. I'm assuming you're getting this
![image](https://user-images.githubusercontent.com/102326872/176307492-f66c944b-3bf3-4913-b0ca-38d61fa55e63.png)

**Comment by VillainsRule4000** [comment]
@CrypticLucid that is not what I am getting on the repo

**Comment by VillainsRule4000** [comment]
@CrypticLucid @SoaRSniping this is not an issue that I'm having...

**Comment by CrypticLucid** [comment]
hmmm. I tried a random one on the deceptive dinos and it gave me the same image. Did you copy the one that is on the repo right now? or are you using an earlier version. I think the earlier versions work but the new ones don't

**Comment by CrypticLucid** [comment]
all of the hacks that were updated 6 or 7 days ago all lead to the same thing but all the older ones still work i.e nocooldown

**Comment by glixxzzy** [comment]
someone hacked my db, mkst work but others dont.

**Comment by CrypticLucid** [comment]
yep i figured. I checked the commits and the anonacc2 guy added some code to the end of every single hack to open up that website

**Comment by CrypticLucid** [comment]
well not website just the text on the screen

**Comment by glixxzzy** [comment]
> yep i figured. I checked the commits and the anonacc2 guy added some code to the end of every single hack to open up that website

Yeah, I'll revert that soon

**Comment by VillainsRule4000** [comment]
@glixxzzy is it true?

**Comment by glixxzzy** [comment]
> @glixxzzy is it true?

Is what true? This person claimed to optimize the hacks but decided just to promote other hacks and try to call me fake which is false, I have reverted this change and my hacks are usable again.

**Comment by glixxzzy** [comment]
As I normally say, I am the only real Gliz unless announced in my Discord server.

**Comment by VillainsRule4000** [comment]
@glixxzzy Why does you Deceptive Dinos code look like rxzyx's?

**Comment by hostedposted** [comment]
> @glixxzzy Why does you Deceptive Dinos code look like rxzyx's?

It is Rxzyz's. This is not the real Gliz.

> @glixxzzy is it true?

Yes it is true.

**Comment by glixxzzy** [comment]
I'm the real gliz and my hack is my own

**Comment by VillainsRule4000** [comment]
IDK who to believe!

**Comment by glixxzzy** [comment]
Novody else has Blooket Wrapper kinda proves something.

**Comment by rxzyx** [comment]
Fun Fact: The wrapper was made by the real gliz, it was patched since it uses WSS Tampering which is an old method! Care to explain?

**Comment by rxzyx** [comment]
This is also why glixxzzy (lol-jude, a vex fake!) can't manage to get spam open box working on the new box, such a shame!

**Comment by rxzyx** [comment]
(If I won't reply, it means that I was blocked) 😀

**Comment by rxzyx** [comment]
Gotta sound cool bruh 😂😂😂 Also WSS Tampering means Websocket Tampering, which is basically sending false requests to a websocket server.

**Comment by rxzyx** [comment]
If you believe glixxzzy, then you are sure a credulous and flunkey person…

**Comment by VillainsRule4000** [comment]
?! Thank you...

**Comment by VillainsRule4000** [comment]
@rxzyx I don't know who to believe, but glixxzzy DOES HAVE YOUR CODE in the commits...

**Comment by rxzyx** [comment]
So betwixt me and him surely that should do it.
