### ISSUE TITLE
Spam Open boxes does not work 

### ISSUE THREAD

**Issue by leowo0k** [glixxzzy/blooket-hack#363]
Or how do you use it

**Comment by theotarr** [comment]
I'm having the same issue with spam open boxes. The injectable throws an error before it even asks what type of box to open. There was a similar issue two commits ago, so I assume this is a running bug. Here are the errors:

```
GET https://api.blooket.com/api/games?gameId=628bf0a5f13fa30455b33c60 404 (Not Found)
```
and
```
Uncaught (in promise) SyntaxError: Unexpected token o in JSON at position 1
````

**Comment by VillainsRule4000** [comment]
@theotarr #327

**Comment by glixxzzy** [comment]
That was someone impersonating me lol

**Comment by leowo0k** [comment]
On Aquatic
