### ISSUE TITLE
Big Box

### ISSUE THREAD

**Issue by L0oax** [glixxzzy/blooket-hack#60]
So when I use these there is a big outline of a box could you fix it, btw love the work keep it up

**Comment by lol-jude** [comment]
You may have to inspect element to remove it but for now I can look into it.

**Comment by Sxber** [comment]
If a outlined box pops up all you have to do is refresh your page.

**Comment by Hankypoo7** [comment]
@Sxber he's talking about if its in game

**Comment by godlygamer123** [comment]
you have to keep it there until the end
